In [22]:
import pandas as pd

In [23]:
alumno = pd.read_csv('csv/alumno.csv')
carrera = pd.read_csv('csv/carrera.csv')
cohorte= pd.read_csv('csv/cohorte.csv')
instructor=pd.read_csv('csv/instructor.csv')

In [24]:
alumno

idAlumno cedulaIdentidad   nombre    apellido fechaNacimiento  \
0           1       274352477  Candice       Rojas      2000-12-10   
1           2       313262855  Beverly     Gardner      2006-10-03   
2           3       335199030   Carlos       Frank      2006-07-11   
3           4       171722128   Callum   Velazquez      2005-11-18   
4           5       14374907K    Kelly  Strickland      2005-11-26   
..        ...             ...      ...         ...             ...   
175       176       335187784     Mara     Rodgers      2004-03-29   
176       177       122874648   Galvin       Jones      2005-11-08   
177       178       386395705   Tashya      Clarke      1992-07-02   
178       179       402918667    Imani        Mack      2000-07-28   
179       180       277347865  William        Long      2009-12-06   

    fechaIngreso  idCohorte  
0     2020-01-21       1235  
1     2019-12-04       1235  
2     2019-12-13       1235  
3     2019-12-17       1235  
4     2019-12-07       1235  
..           ...        ...  
175   2022-02-13       1243  
176   2022-01-06       1243  
177   2022-01-31       1243  
178   2022-01-29       1243  
179   2022-02-09       1243  

[180 rows x 7 columns]

In [25]:
carrera

idCarrera                nombre
0          1  Full Stack Developer
1          2          Data Science

In [26]:
cohorte

idCohorte   codigo  idCarrera  idInstructor fechaInicio fechaFinalizacion
0        1235  FT-1235          1             1  2020-02-01        2020-06-30
1        1236  FT-1236          1             2  2020-04-05        2020-08-31
2        1237  FT-1237          1             1  2021-07-05        2021-11-30
3        1238  FT-1238          1             2  2021-09-06        2022-01-31
4        1239  FT-1239          1             3  2022-01-10               NaN
5        1240  FT-1240          1             4  2022-02-07               NaN
6        1241  FT-1241          1             5  2022-03-07               NaN
7        1242  DS-1242          2             6  2022-03-28               NaN
8        1243  FT-1243          1             1  2022-04-04               NaN
9        1244  DS-1244          2             8  2022-05-02               NaN
10       1245  FT-1245          1             2  2022-05-02               NaN
11       1246  DS-1246          2             7  2022-07-04               NaN
12       1247  FT-1235          1             1  2020-02-01        2020-06-30

In [27]:
instructor

idInstructor  cedulaIdentidad    nombre   apellido fechaNacimiento  \
0             1         25456879   Antonio    Barrios      1981-07-09   
1             2         28456321     Lucia  Fernandez      1992-05-25   
2             3         27198354       Leo      Paris      1985-06-20   
3             4         36987520   Agustín    Casagne      1988-08-17   
4             5         33456215    Franco    Caseros      1995-05-01   
5             6         30521369     Dario    Ramirez      1989-07-20   
6             7         28856789  Agustina     Medina      1991-03-08   
7             8         33128987     Jorge      Perez      1988-02-19   

  fechaIncorporacion  
0         2019-11-08  
1         2019-11-08  
2         2021-08-15  
3         2021-08-15  
4         2021-08-15  
5         2021-12-01  
6         2021-12-01  
7         2021-12-01

2.	No se sabe con certeza el lanzamiento de las cohortes N° 1245 y N° 1246, se solicita que las elimine de la tabla.<br>

In [28]:
cohorte[(cohorte['idCohorte']==1245) | (cohorte['idCohorte']==1246)]

idCohorte   codigo  idCarrera  idInstructor fechaInicio fechaFinalizacion
10       1245  FT-1245          1             2  2022-05-02               NaN
11       1246  DS-1246          2             7  2022-07-04               NaN

In [29]:
borrar=(cohorte['idCohorte']==1245) | (cohorte['idCohorte']==1246)
cohorte=cohorte[~borrar]
cohorte

idCohorte   codigo  idCarrera  idInstructor fechaInicio fechaFinalizacion
0        1235  FT-1235          1             1  2020-02-01        2020-06-30
1        1236  FT-1236          1             2  2020-04-05        2020-08-31
2        1237  FT-1237          1             1  2021-07-05        2021-11-30
3        1238  FT-1238          1             2  2021-09-06        2022-01-31
4        1239  FT-1239          1             3  2022-01-10               NaN
5        1240  FT-1240          1             4  2022-02-07               NaN
6        1241  FT-1241          1             5  2022-03-07               NaN
7        1242  DS-1242          2             6  2022-03-28               NaN
8        1243  FT-1243          1             1  2022-04-04               NaN
9        1244  DS-1244          2             8  2022-05-02               NaN
12       1247  FT-1235          1             1  2020-02-01        2020-06-30

3.	Se ha decidido retrasar el comienzo de la cohorte N°1243, por lo que la nueva fecha de inicio será el 16/05. Se le solicita modificar la fecha de inicio de esos alumnos.

In [30]:
cohorte[cohorte['idCohorte']==1243]

idCohorte   codigo  idCarrera  idInstructor fechaInicio fechaFinalizacion
8       1243  FT-1243          1             1  2022-04-04               NaN

In [31]:
cohorte.loc[cohorte['idCohorte']==1243, 'fechaInicio']='2023-05-16'

In [32]:
cohorte[cohorte['idCohorte']==1243]

idCohorte   codigo  idCarrera  idInstructor fechaInicio fechaFinalizacion
8       1243  FT-1243          1             1  2023-05-16               NaN

4.	El alumno N° 165 solicito el cambio de su Apellido por “Ramirez”.

In [33]:
alumno[alumno['idAlumno']==165]

idAlumno cedulaIdentidad  nombre apellido fechaNacimiento fechaIngreso  \
164       165       377028562  Regina    Joyce      2002-07-05   2022-02-08   

     idCohorte  
164       1243

In [34]:
alumno.loc[alumno['idAlumno']==165, 'apellido'] = 'Ramirez'

In [35]:
alumno[alumno['idAlumno']==165]

idAlumno cedulaIdentidad  nombre apellido fechaNacimiento fechaIngreso  \
164       165       377028562  Regina  Ramirez      2002-07-05   2022-02-08   

     idCohorte  
164       1243

5.	El área de Learning le solicita un listado de alumnos de la Cohorte N°1243 que incluya la fecha de ingreso.

In [36]:
alumno[alumno['idCohorte']==1243]

idAlumno cedulaIdentidad     nombre  apellido fechaNacimiento  \
160       161        41944781  Stephanie     Hurst      1986-11-23   
161       162        31806976  Nathaniel     Duran      2005-12-02   
162       163        9364994K    Shelley      Yang      1984-01-14   
163       164       263549317    Donovan      Snow      2008-07-23   
164       165       377028562     Regina   Ramirez      2002-07-05   
165       166         7332238     Hedley   Cameron      2002-06-05   
166       167       448157210    Kiayada     Oneil      2009-03-26   
167       168       123492919  Aristotle     Adams      2000-09-29   
168       169       182865443     Harlan   Barnett      1997-10-19   
169       170       389678961       Maya    Dotson      2003-11-28   
170       171       152989121       Sean   Hancock      1997-09-21   
171       172       507078060     Arthur      Leon      2006-12-01   
172       173        72477197     Hakeem  Williams      1988-03-13   
173       174        41643293      Nigel   Vincent      2001-10-06   
174       175       454734130      Adele    Alston      2005-10-05   
175       176       335187784       Mara   Rodgers      2004-03-29   
176       177       122874648     Galvin     Jones      2005-11-08   
177       178       386395705     Tashya    Clarke      1992-07-02   
178       179       402918667      Imani      Mack      2000-07-28   
179       180       277347865    William      Long      2009-12-06   

    fechaIngreso  idCohorte  
160   2022-02-14       1243  
161   2022-01-03       1243  
162   2022-01-18       1243  
163   2022-02-09       1243  
164   2022-02-08       1243  
165   2022-01-12       1243  
166   2022-02-25       1243  
167   2022-01-18       1243  
168   2022-02-09       1243  
169   2022-01-14       1243  
170   2022-02-22       1243  
171   2022-02-15       1243  
172   2022-01-21       1243  
173   2022-01-31       1243  
174   2022-01-16       1243  
175   2022-02-13       1243  
176   2022-01-06       1243  
177   2022-01-31       1243  
178   2022-01-29       1243  
179   2022-02-09       1243

6.	Como parte de un programa de actualización, el área de People le solicita un listado de los instructores que dictan la carrera de Full Stack Developer

In [37]:
unido=pd.merge(instructor,cohorte, on='idInstructor')
unido=pd.merge(unido,carrera, on='idCarrera')
unido=unido[unido['nombre_y']=='Full Stack Developer']
unido

idInstructor  cedulaIdentidad nombre_x   apellido fechaNacimiento  \
0             1         25456879  Antonio    Barrios      1981-07-09   
1             1         25456879  Antonio    Barrios      1981-07-09   
2             1         25456879  Antonio    Barrios      1981-07-09   
3             1         25456879  Antonio    Barrios      1981-07-09   
4             2         28456321    Lucia  Fernandez      1992-05-25   
5             2         28456321    Lucia  Fernandez      1992-05-25   
6             3         27198354      Leo      Paris      1985-06-20   
7             4         36987520  Agustín    Casagne      1988-08-17   
8             5         33456215   Franco    Caseros      1995-05-01   

  fechaIncorporacion  idCohorte   codigo  idCarrera fechaInicio  \
0         2019-11-08       1235  FT-1235          1  2020-02-01   
1         2019-11-08       1237  FT-1237          1  2021-07-05   
2         2019-11-08       1243  FT-1243          1  2023-05-16   
3         2019-11-08       1247  FT-1235          1  2020-02-01   
4         2019-11-08       1236  FT-1236          1  2020-04-05   
5         2019-11-08       1238  FT-1238          1  2021-09-06   
6         2021-08-15       1239  FT-1239          1  2022-01-10   
7         2021-08-15       1240  FT-1240          1  2022-02-07   
8         2021-08-15       1241  FT-1241          1  2022-03-07   

  fechaFinalizacion              nombre_y  
0        2020-06-30  Full Stack Developer  
1        2021-11-30  Full Stack Developer  
2               NaN  Full Stack Developer  
3        2020-06-30  Full Stack Developer  
4        2020-08-31  Full Stack Developer  
5        2022-01-31  Full Stack Developer  
6               NaN  Full Stack Developer  
7               NaN  Full Stack Developer  
8               NaN  Full Stack Developer

In [38]:
unido.columns

Index(['idInstructor', 'cedulaIdentidad', 'nombre_x', 'apellido',
       'fechaNacimiento', 'fechaIncorporacion', 'idCohorte', 'codigo',
       'idCarrera', 'fechaInicio', 'fechaFinalizacion', 'nombre_y'],
      dtype='object')

In [39]:
unido[['idInstructor', 'nombre_x', 'apellido', 'nombre_y']].drop_duplicates(subset=['idInstructor', 'nombre_x', 'apellido'])

idInstructor nombre_x   apellido              nombre_y
0             1  Antonio    Barrios  Full Stack Developer
4             2    Lucia  Fernandez  Full Stack Developer
6             3      Leo      Paris  Full Stack Developer
7             4  Agustín    Casagne  Full Stack Developer
8             5   Franco    Caseros  Full Stack Developer

7. Se desea saber que alumnos formaron parte de la cohorte N° 1235. Elabore un listado.

In [43]:
alumno.columns

Index(['idAlumno', 'cedulaIdentidad', 'nombre', 'apellido', 'fechaNacimiento',
       'fechaIngreso', 'idCohorte'],
      dtype='object')

In [44]:
alumno[alumno['idCohorte']==1235][['nombre', 'apellido', 'idCohorte']]

nombre    apellido  idCohorte
0     Candice       Rojas       1235
1     Beverly     Gardner       1235
2      Carlos       Frank       1235
3      Callum   Velazquez       1235
4       Kelly  Strickland       1235
5       Drake     Pearson       1235
6       Aimee       Cline       1235
7      Julian    Copeland       1235
8     Cecilia        Roth       1235
9     Hillary      Holman       1235
10   Odysseus     Solomon       1235
11     Jemima     Carlson       1235
12      Boris        Lamb       1235
13     Sierra        Cook       1235
14    Michael      Norton       1235
15  Whilemina      Howard       1235
16     Keegan       Mejia       1235
17       Dawn        Duke       1235
18    Lillith      Conley       1235
19    Marsden      Sparks       1235

8. Del listado anterior se desea saber quienes ingresaron en el año 2019

In [51]:
alumno[(alumno['idCohorte']==1235)].loc[alumno['fechaIngreso'].str.contains('2019')]

idAlumno cedulaIdentidad    nombre    apellido fechaNacimiento  \
1          2       313262855   Beverly     Gardner      2006-10-03   
2          3       335199030    Carlos       Frank      2006-07-11   
3          4       171722128    Callum   Velazquez      2005-11-18   
4          5       14374907K     Kelly  Strickland      2005-11-26   
5          6       49205318K     Drake     Pearson      2009-08-08   
7          8       401797157    Julian    Copeland      2001-01-09   
8          9         4257391   Cecilia        Roth      2004-12-01   
9         10        19507661   Hillary      Holman      2001-04-07   
10        11       106717451  Odysseus     Solomon      2009-07-01   
11        12       289307281    Jemima     Carlson      2009-08-26   
16        17        1114943K    Keegan       Mejia      2001-01-29   
18        19       435719201   Lillith      Conley      2004-04-16   
19        20        15903996   Marsden      Sparks      2004-04-16   

   fechaIngreso  idCohorte  
1    2019-12-04       1235  
2    2019-12-13       1235  
3    2019-12-17       1235  
4    2019-12-07       1235  
5    2019-12-30       1235  
7    2019-12-05       1235  
8    2019-12-17       1235  
9    2019-12-14       1235  
10   2019-12-14       1235  
11   2019-12-09       1235  
16   2019-12-29       1235  
18   2019-12-11       1235  
19   2019-12-25       1235

In [53]:
#ejemplo solo idCohorte=1235
alumno[(alumno['idCohorte']==1235)]

idAlumno cedulaIdentidad     nombre    apellido fechaNacimiento  \
0          1       274352477    Candice       Rojas      2000-12-10   
1          2       313262855    Beverly     Gardner      2006-10-03   
2          3       335199030     Carlos       Frank      2006-07-11   
3          4       171722128     Callum   Velazquez      2005-11-18   
4          5       14374907K      Kelly  Strickland      2005-11-26   
5          6       49205318K      Drake     Pearson      2009-08-08   
6          7       398182472      Aimee       Cline      2009-11-19   
7          8       401797157     Julian    Copeland      2001-01-09   
8          9         4257391    Cecilia        Roth      2004-12-01   
9         10        19507661    Hillary      Holman      2001-04-07   
10        11       106717451   Odysseus     Solomon      2009-07-01   
11        12       289307281     Jemima     Carlson      2009-08-26   
12        13        38156527      Boris        Lamb      2006-04-24   
13        14        47873452     Sierra        Cook      2005-05-16   
14        15       112197338    Michael      Norton      2007-07-01   
15        16        84091987  Whilemina      Howard      2000-12-03   
16        17        1114943K     Keegan       Mejia      2001-01-29   
17        18        32392091       Dawn        Duke      2006-07-13   
18        19       435719201    Lillith      Conley      2004-04-16   
19        20        15903996    Marsden      Sparks      2004-04-16   

   fechaIngreso  idCohorte  
0    2020-01-21       1235  
1    2019-12-04       1235  
2    2019-12-13       1235  
3    2019-12-17       1235  
4    2019-12-07       1235  
5    2019-12-30       1235  
6    2020-01-26       1235  
7    2019-12-05       1235  
8    2019-12-17       1235  
9    2019-12-14       1235  
10   2019-12-14       1235  
11   2019-12-09       1235  
12   2020-01-13       1235  
13   2020-01-25       1235  
14   2020-01-11       1235  
15   2020-01-07       1235  
16   2019-12-29       1235  
17   2020-01-30       1235  
18   2019-12-11       1235  
19   2019-12-25       1235

In [54]:
#ejemplo solo año de ingreso 2019
alumno.loc[alumno['fechaIngreso'].str.contains('2019')]

idAlumno cedulaIdentidad    nombre    apellido fechaNacimiento  \
1          2       313262855   Beverly     Gardner      2006-10-03   
2          3       335199030    Carlos       Frank      2006-07-11   
3          4       171722128    Callum   Velazquez      2005-11-18   
4          5       14374907K     Kelly  Strickland      2005-11-26   
5          6       49205318K     Drake     Pearson      2009-08-08   
7          8       401797157    Julian    Copeland      2001-01-09   
8          9         4257391   Cecilia        Roth      2004-12-01   
9         10        19507661   Hillary      Holman      2001-04-07   
10        11       106717451  Odysseus     Solomon      2009-07-01   
11        12       289307281    Jemima     Carlson      2009-08-26   
16        17        1114943K    Keegan       Mejia      2001-01-29   
18        19       435719201   Lillith      Conley      2004-04-16   
19        20        15903996   Marsden      Sparks      2004-04-16   

   fechaIngreso  idCohorte  
1    2019-12-04       1235  
2    2019-12-13       1235  
3    2019-12-17       1235  
4    2019-12-07       1235  
5    2019-12-30       1235  
7    2019-12-05       1235  
8    2019-12-17       1235  
9    2019-12-14       1235  
10   2019-12-14       1235  
11   2019-12-09       1235  
16   2019-12-29       1235  
18   2019-12-11       1235  
19   2019-12-25       1235